create table users (id int, name text, city text);
insert into users values (1, 'tomer', 'haifa');
insert into users values (2, 'dana', 'tel aviv');
insert into users values (3, 'yossi', 'haifa');
create table orders (oid int, uid int, total int);
insert into orders values (10, 1, 250);
insert into orders values (11, 1, 90);
insert into orders values (12, 2, 400);
insert into orders values (13, 9, 5);
select * from users, orders where users.id = orders.uid;
select name, total from users, orders where users.id = orders.uid;
select users.name, orders.total from users, orders where users.id = orders.uid and total > 100 order by total desc;
select name, sum(total) from users, orders where users.id = orders.uid group by name;
select name, count(*) from users, orders where users.id = orders.uid group by name having count(*) > 1;
select distinct city from users, orders where users.id = orders.uid;
select count(*) from users, orders;
create table items (item text, price int);
insert into items values ('book', 30);
insert into items values ('pen', 5);
create table lines (uid int, item text);
insert into lines values (1, 'book');
insert into lines values (2, 'pen');
select name, lines.item, price from users, lines, items where users.id = lines.uid and lines.item = items.item order by price desc;
select users.name from users where users.id = 2;
select name, total from users join orders on users.id = orders.uid;
select name, total from users inner join orders on users.id = orders.uid where total > 100;
select name, total from users join orders on id = uid and total > 100;
select name, lines.item, price from users join lines on users.id = lines.uid join items on lines.item = items.item order by price desc;
