create table emp (id int, name text, boss int, dept text);
insert into emp values (1, 'tomer', 3, 'eng');
insert into emp values (2, 'dana', 3, 'eng');
insert into emp values (3, 'yossi', null, 'eng');
insert into emp values (4, 'maya', 3, 'sales');
select e.name, b.name from emp e, emp b where e.boss = b.id order by e.name;
select e.name as worker, b.name as manager from emp e join emp b on e.boss = b.id order by worker;
select a.name, b.name from emp a, emp b where a.id < b.id and a.dept = b.dept order by a.name, b.name;
select name from emp e order by name;
select * from emp e limit 2;
select e.dept, count(*) from emp as e group by e.dept order by e.dept;
select dept as d, count(*) as headcount from emp group by dept order by headcount desc;
select name n from emp where dept = 'sales';
select dept, count(*) as c from emp group by dept having c > 2;
select emp.name from emp order by name;
select count(*) as total from emp;
select e.name from emp e, emp e;
select emp.name from emp e;
select x.name from emp e;
